const pools={
ex1:[
["She is tall. → I","I am tall."],["She has long brown hair. → I","I have long brown hair."],["I am slim. → He","He is slim."],["I have blue eyes. → She","She has blue eyes."],["She isn't short. → They","They aren't short.|They are not short."],["They don't have glasses. → He","He doesn't have glasses.|He does not have glasses."],["He is short. → We","We are short."],["I am tall. → She","She is tall."],["They are slim. → He","He is slim."],["We have green eyes. → She","She has green eyes."],["He has curly hair. → I","I have curly hair."],["She has glasses. → They","They have glasses."],["I don't have glasses. → He","He doesn't have glasses.|He does not have glasses."],["He isn't tall. → I","I am not tall.|I'm not tall."],["They have blond hair. → She","She has blond hair."],["We are short. → He","He is short."],["She is slim. → They","They are slim."],["He has brown eyes. → I","I have brown eyes."],["I have short hair. → She","She has short hair."],["They aren't slim. → She","She isn't slim.|She is not slim."],["We don't have blue eyes. → He","He doesn't have blue eyes.|He does not have blue eyes."],["She has long hair. → I","I have long hair."],["I am short. → They","They are short."],["He is tall. → We","We are tall."],["They have glasses. → She","She has glasses."],["She doesn't have curly hair. → They","They don't have curly hair.|They do not have curly hair."],["I am not slim. → He","He isn't slim.|He is not slim."],["He has green eyes. → We","We have green eyes."],["We have black hair. → She","She has black hair."],["They are tall. → I","I am tall."]],
ex2:[
["Lucy ___ tall and slim.","is"],["She ___ long brown hair.","has"],["She ___ blue eyes.","has"],["Her brother ___ short.","is"],["He ___ curly black hair.","has"],["They ___ very tall.","are"],["Lucy ___ glasses.","has"],["Her brother ___ green eyes.","has"],["I ___ slim.","am"],["We ___ brown eyes.","have"],["Tom ___ tall.","is"],["My friends ___ blond hair.","have"],["You ___ very tall.","are"],["Anna ___ short hair.","has"],["I ___ blue eyes.","have"],["They ___ slim.","are"],["He ___ glasses.","has"],["We ___ tall.","are"],["My sister ___ curly hair.","has"],["You ___ green eyes.","have"],["Emma ___ short.","is"],["The boys ___ brown hair.","have"],["My brother ___ slim.","is"],["I ___ long hair.","have"],["She ___ tall.","is"],["They ___ glasses.","have"],["We ___ short.","are"],["Jack ___ blue eyes.","has"],["You ___ slim.","are"],["I ___ short brown hair.","have"]],
ex3:[
["She has / hair / long / brown.","She has long brown hair."],["He has / eyes / blue / big.","He has big blue eyes."],["She is wearing / a / skirt / black.","She is wearing a black skirt."],["He has / hair / curly / short / blond.","He has short curly blond hair.|He has short blond curly hair."],["She is wearing / shoes / black / beautiful.","She is wearing beautiful black shoes."],["He is wearing / a / jumper / blue / big.","He is wearing a big blue jumper."],["She has / hair / long / blond.","She has long blond hair."],["He has / eyes / green / big.","He has big green eyes."],["She is wearing / a / dress / red / beautiful.","She is wearing a beautiful red dress."],["He is wearing / shoes / brown / big.","He is wearing big brown shoes."],["She has / hair / short / black.","She has short black hair."],["He is wearing / a / T-shirt / white / big.","He is wearing a big white T-shirt."],["She has / eyes / brown / beautiful.","She has beautiful brown eyes."],["He has / hair / short / brown.","He has short brown hair."],["She is wearing / a / jumper / green / big.","She is wearing a big green jumper."],["He has / eyes / blue / beautiful.","He has beautiful blue eyes."],["She has / hair / curly / long / brown.","She has long curly brown hair.|She has long brown curly hair."],["He is wearing / trousers / black / big.","He is wearing big black trousers."],["She is wearing / shoes / white / beautiful.","She is wearing beautiful white shoes."],["He has / hair / blond / short.","He has short blond hair."],["She is wearing / a / skirt / blue / beautiful.","She is wearing a beautiful blue skirt."],["He has / eyes / brown / big.","He has big brown eyes."],["She has / hair / straight / long / black.","She has long straight black hair.|She has long black straight hair."],["He is wearing / a / jacket / black / big.","He is wearing a big black jacket."],["She has / eyes / green / beautiful.","She has beautiful green eyes."],["He has / hair / curly / brown / short.","He has short curly brown hair.|He has short brown curly hair."],["She is wearing / a / T-shirt / red / beautiful.","She is wearing a beautiful red T-shirt."],["He is wearing / shoes / blue / big.","He is wearing big blue shoes."],["She has / hair / brown / long.","She has long brown hair."],["He is wearing / a / jumper / grey / beautiful.","He is wearing a beautiful grey jumper."]]
};
function norm(s){return s.trim().toLowerCase().replace(/[’]/g,"'").replace(/\s+/g,' ').replace(/[.!?]+$/,'')}
function pick(a,n=10){return [...a].sort(()=>Math.random()-.5).slice(0,n)}
function render(id){const box=document.getElementById(id);box.innerHTML='';pick(pools[id]).forEach((item,i)=>{const d=document.createElement('div');d.className='q';d.innerHTML=`<div class="prompt">${i+1}. ${item[0]}</div><input data-answers="${item[1].replace(/"/g,'&quot;')}" autocomplete="off"><div class="feedback"></div>`;box.appendChild(d)});document.getElementById('score-'+id).textContent=''}
function check(id){let good=0;const qs=[...document.querySelectorAll('#'+id+' .q')];qs.forEach(q=>{const inp=q.querySelector('input'),fb=q.querySelector('.feedback');const answers=inp.dataset.answers.split('|');const ok=answers.some(a=>norm(a)===norm(inp.value));if(ok){good++;fb.className='feedback ok';fb.textContent='✓ Correct!'}else{fb.className='feedback no';fb.textContent='✗ Correct answer: '+answers[0]}});document.getElementById('score-'+id).textContent=`Score: ${good} / ${qs.length}`}
['ex1','ex2','ex3'].forEach(render);
